name: Create Release Zip

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Set VERSION variable in Lua file
        run: |
          sed -i "s/VERSION = .*/VERSION = \"${{ env.VERSION }}\"/" xa-cabin/globals.lua
          rm -rf .git
          rm -rf .github
          rm -rf .vscode
          rm -rf scripts
      
      # covert markdown file to pdf
      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
      - name: Convert markdown to PDF
        run: |
          pandoc profiles/README.md -o profiles/README.pdf
          rm -rf profiles/README.md

      - name: Zip the code
        run: zip -r release-${{ env.VERSION }}.zip .

      - name: Read Changelog
        id: read_changelog
        run: echo "::set-output name=changelog::$(cat changelog.md)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: ${{ steps.read_changelog.outputs.changelog }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step.
          asset_path: ./release-${{ env.VERSION }}.zip
          asset_name: release-${{ env.VERSION }}.zip
          asset_content_type: application/zip
